BookConferenceHallApp/urls.py
from django.conf.urls import url
from BookConferenceHallApp.views import *

app_name = 'book'
urlpatterns = [
    url(r'^$', index, name="home"),
    url(r'^Hall/(?P<id>(\d)+)$', Hall, name="Hall"),
    url(r'^Hall/new$', NewHallView.as_view(), name="new-Hall"),
    url(r'^Hall/modify/(?P<id>(\d)+)$', ModifyView.as_view(), name="modify"),
    url(r'^Hall/delete/(?P<id>(\d)+)$', DeleteView.as_view(), name="delete"),
    url(r'^Hall/reservation/(?P<id>(\d)+)$', ReservationView.as_view(), name="reservation"),
    url(r'^search$', SearchView.as_view(), name="search"),

]

DjangoCLProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('BookConferenceHallApp.urls')),

]

BookConferenceHallApp/models.py
from django.db import models

# Create your models here.


class Hall(models.Model):
    name = models.CharField(max_length=64)
    capacity = models.IntegerField()
    projector = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Reservation(models.Model):
    Hall = models.ManyToManyField(Hall)
    date = models.DateField()
    comment = models.TextField()

    def __str__(self):
        for r in self.Hall.all():
            return "Date of booking: {}, conference Hall: {}".format(self.date, r.name)

BookConferenceHallApp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from datetime import datetime

from .models import *

# Create your views here.

today = datetime.today().strftime('%Y-%m-%d')


def index(request):
    Halls = Hall.objects.all()
    status = {}

    for Hall in Halls:
        if Hall.reservation_set.filter(date=today):
            status[Hall.id] = 'Busy'
        else:
            status[Hall.id] = 'Free'
    ctx = {
        'Halls': Halls,
        'status': status,
    }
    return render(request, 'Book/index.html', ctx)


def Hall(request, id):
    Hall = Hall.objects.get(pk=int(id))
    if Hall:
        reservations = Hall.reservation_set.filter(date__gte=today).order_by('date')
        Halls = Hall.objects.all()
        if Hall.projector == True:
            projector = "Yes"
        else:
            projector = "No"
        ctx = {
            "Hall": Hall,
            "projector": projector,
            "reservations": reservations,
            "Halls": Halls,
        }
    else:
        ctx = {
            "Hall": 'Hall Not Available',
            "projector": 'NA',
            "reservations": 'NA',
            "Halls": 'NA',
        }
    return render(request, 'Book/Hall.html', ctx)


class NewHallView(View):

    def get(self, request):
        return render(request, 'Book/new_Hall.html')

    def post(self, request):
        try:
            name = request.POST.get("name")
            capacity = request.POST.get("capacity")
            projector = request.POST.get("projector")
            proj = True if projector == "True" else False

            Hall.objects.create(name=name, capacity=capacity, projector=proj)
            return redirect("/")

        except Exception as e:
            message = "Incorrect Data: {}".format(e)
            ctx = {
                "message": message,
            }
            return render(request, 'Book/new_Hall.html', ctx)


class ModifyView(View):

    def get(self, request, id):
        Hall = Hall.objects.get(pk=id)
        ctx = {
            "Hall": Hall,
        }
        return render(request, 'Book/modify.html', ctx)

    def post(self, request, id):
        name = request.POST.get("name")
        capacity = request.POST.get("capacity")
        projector = True if request.POST.get('projector') else False
        Hall = Hall.objects.get(pk=id)
        try:
            Hall.name = name
            Hall.capacity = capacity
            Hall.projector = projector
            Hall.save()
            return redirect("/")
        except Exception as e:
            message = "Incorrect Data: {}".format(e)
            ctx = {
                "message": message,
                "Hall": Hall,
            }
            return render(request, 'Book/modify.html', ctx)


class DeleteView(View):

    def get(self, request, id):
        Hall = Hall.objects.get(pk=id)
        ctx = {
            "Hall": Hall,
        }
        return render(request, 'Book/delete.html', ctx)

    def post(self, request, id):
        action = request.POST.get("submit")

        if action == "Yes":
            Hall = Hall.objects.get(pk=id)
            Hall.delete()
        return redirect("/")


class ReservationView(View):

    def get(self, request, id):
        Hall = Hall.objects.get(pk=id)
        reservations = Hall.reservation_set.filter(date__gte=today).order_by('date')
        ctx = {
            "Hall": Hall,
            "reservations": reservations,
        }
        return render(request, 'Book/reservation.html', ctx)

    def post(self, request, id):
        Hall = Hall.objects.get(pk=id)
        reservations = Hall.reservation_set.filter(date__gte=today).order_by('date')
        try:
            date = request.POST.get("date")
            comment = request.POST.get("comment")
            message = ""

            if Hall.reservation_set.filter(date=date):
                message = "This Hall is already occupied for that day"
            elif date < today:
                message = "The chosen data can not be in the past"

            if (message == "This Hall is already occupied for that day"
                or message == "The chosen data can not be in the past"):
                ctx = {
                    "Hall": Hall,
                    "reservations": reservations,
                    "message": message,
                }
                return render(request, 'Book/reservation.html', ctx)

            reservation = Reservation.objects.create(date=date, comment=comment)
            reservation.Hall.add(Hall)

        except Exception as e:
            message = "Incorrect Data: {}".format(e)
            ctx = {
                "message": message,
                "Hall": Hall,
                "reservations": reservations,
            }
            return render(request, 'Book/reservation.html', ctx)

        if Hall.projector == True:
            projector = "TAK"
        else:
            projector = "NIE"
        message = """Dziękujemy! Zarezerwowałeś salę: 
                     {} w dniu: {}""".format(Hall.name, date)
        ctx = {
            "Hall": Hall,
            "projector": projector,
            "reservations": reservations,
            "message": message,
        }
        return render(request, 'Book/Hall.html', ctx)


class SearchView(View):

    def get(self, request):
        Hall = request.GET.get("Hall")
        capacity = request.GET.get("capacity")
        date = request.GET.get("date")
        projector = True if request.GET.get('projector') else False

        result1 = Hall.objects.exclude(reservation__date=date)

        if Hall == "":
            result2 = result1
        else:
            result2 = result1.filter(name__icontains=Hall)

        if capacity != "":
            result3 = result2.filter(capacity__gte=int(capacity))
        else:
            result3 = result2

        if projector:
            result4 = result3.filter(projector=projector)
        else:
            result4 = result3

        ctx = {
            "results": result4,
            "date": date,
        }
        return render(request, 'Book/search.html', ctx)

BookConferenceHallApp/templates/Book/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
          crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-info navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link lead text-dark" href="{% url 'book:home' %}">HOME </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link lead text-dark" href="{% url 'book:new-room' %}">NEW ROOM </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link lead text-dark" href="/#search">FIND A ROOM </a>
                </li>
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

BookConferenceHallApp/templates/Book/delete.html
{% extends 'Book/base.html' %}

{% block title %}Delete the room{% endblock %}

{% block content %}
    <br/>
    <h2>Are you sure you want to delete room: {{ room.name }}</h2>
    <form method="POST" action="#">
    {% csrf_token %}
        <input class="btn btn-success" type="submit" name="submit" value="Yes">
        <input class="btn btn-danger" type="submit" name="submit" value="No">
    </form>
{% endblock %}

BookConferenceHallApp/templates/Book/index.html
{% extends 'Book/base.html' %}

{% block title %}Conference Room{% endblock %}

{% block content %}
    <br/>
    <h2>All Conference Rooms</h2>
    <table class="table table-striped table-bordered">
        <tr>
            <thead class="thead lead">
                <th>ROOM NAME</th>
                <th>CAPACITY</th>
                <th>STATUS</th>
                <th>MODIFY</th>
                <th>DELETE</th>
            </thead>
        </tr>
        {% for room in rooms %}
        <tr>
            <td><a href="{% url 'book:room' room.id %}">{{ room.name }}</a></td>
            <td>{{ room.capacity }}</td>
            {% for k,v in status.items %}
                {% if room.id == k %}
                    <td{% if v == "Free" %} class="text-success"
                    {% else %} class="text-danger" {% endif %}>{{ v }}</td>
                {% endif %}
            {% endfor %}
            <td><a href="{% url 'book:modify' room.id %}"><button class="btn btn-warning">modify</button></a></td>
            <td><a href="{% url 'book:delete' room.id %}"><button class="btn btn-danger">remove</button></a></td>
        </tr>
        {% endfor %}
    </table>
    <a href="{% url 'book:new-room' %}">
        <button class="btn btn-success">Create New Conference Room</button>
    </a><br/><br/>
    <div class="jumbotron">
        <h3>SEARCH FOR AVAILABLE ROOM</h3>
        <br/>
        <form id="search" method="get" action="{% url 'book:search' %}">
            <label>ROOM NAME
                <input type="text" name="room">
            </label><br/>
            <label>MINIMUM CAPACITY
                <input type="number" name="capacity">
            </label><br/>
            <label>BOOKING DATE
                <input type="date" name="date" required="required">
            </label><br/>
            <label>PROJECTOR
                <input type="checkbox" name="projector">
            </label><br/>
                <input type="submit" value="Search" class="btn btn-warning">
        </form>
    </div>

{% endblock %}

BookConferenceHallApp/templates/Book/modify.html
{% extends 'Book/base.html' %}

{% block title %}Modify room{% endblock %}

{% block content %}
    <br/>
    <h2>Conference room modification: {{ room.name }}</h2>
    <p class="text-danger">{{ message }}</p>
    <form method="POST" action="#">
    {% csrf_token %}
        <label>Living room
            <input type="text" name="name" value="{{ room.name }}" class="form-control">
        </label>
        <br/>
        <label>Capacity:
            <input type="number" name="capacity", value="{{ room.capacity }}" class="form-control">
        </label>
        <br/>
        {% if room.projector == True %}
        <input type="checkbox" name="projector" checked="checked"> Projector
        {% else %}
        <input type="checkbox" name="projector"> Projector
        {% endif %}
        <br/>
        <br/>
        <input class="btn btn-warning" type="submit" value="MODIFY">
    </form>
{% endblock %}

BookConferenceHallApp/templates/Book/new_room.html
{% extends 'Book/base.html' %}

{% block title %}Add a Hall{% endblock %}

{% block content %}

    <br/>
    <h2>Create a new conference Hall</h2>
    <p class="text-danger">{{ message }}</p>
    <form method="POST" action="#">
    {% csrf_token %}
        <label>Hall NAME
            <input type="text" name="name" class="form-control" required="required">
        </label><br/>
        <label>Hall CAPACITY
            <input type="number" name="capacity" placeholder="e.g. 50"
                   class="form-control" required="required">
        </label><br/>
        <label>IS THERE A PROJECTOR:
            <input type="radio" name="projector" value="True">Yes
            <input type="radio" name="projector" value="False">No
        </label><br/>
        <input class="btn btn-success" type="submit" value="CREATE">
    </form>

{% endblock %}

BookConferenceHallApp/templates/Book/reservation.html
{% extends 'Book/base.html' %}

{% block title %}Reservation{% endblock %}

{% block content %}
    <br/>
    <table class="table table-bordered table-striped">
        <tr>
            <td>Conference Hall:</td>
            <td>{{ Hall.name }}</td>
        </tr>
        <tr>
            <td>Occupied Dates:</td>
            <td>
                {% for book in reservations %}
                {{ book }}<br/>
                {% endfor %}
            </td>
        </tr>
    </table>

    <h2>Book a Conference hall - Hall {{ Hall.name }}</h2>
    <p class="text-danger">{{ message }}</p>

    <form method="post" action="#">
    {% csrf_token %}
        <label>Data:
            <input type="date" name="date" required="required">
        </label><br/>
        <label>Additional remarks:<br/>
            <textarea name="comment" class="form-control">Lack of Availability</textarea>
        </label><br/>
        <input type="submit" name="submit" value="Book It" class="btn btn-success">
    </form>
    <br>
    <a href="{% url 'book:Hall' Hall.id %}"><button class="btn btn-warning">Back to the view of the Hall</button></a>
{% endblock %}

BookConferenceHallApp/templates/Book/room.html
{% extends 'Book/base.html' %}

{% block title %}Room details{% endblock %}

{% block content %}
    <br/>
    <table class="table table-bordered table-striped">
        <tr>
            <td>Conference room</td>
            <td class="lead">{{ room.name|upper }}</td>
        </tr>
        <tr>
            <td>Capacity</td>
            <td>{{ room.capacity }}</td>
        </tr>
        <tr>
            <td>Projector</td>
            <td>{{ projector }}</td>
        </tr>
        <tr>
            <td>The room is busy</td>
            <td>{% for reservation in reservations %}{{ reservation }}<br/>{% endfor %}</td>
        </tr>
        <tr>
            <td>Book a room</td>
            <td>
                <a href="{% url 'book:reservation' room.id %}">
                <button class="btn btn-success">Book It</button></a>
            </td>
        </tr>
    </table>
    <br/>

    {% if room.id > 1 %}
        <a href="{% url 'book:room' room.id|add:'-1' %}">
            <button class="btn btn-warning">Hot Hall</button>
        </a>
    {% else %}
        <a href="{% url 'book:room' rooms|length %}">
            <button class="btn btn-warning">Hot Hall</button>
        </a>
    {% endif %}

    {% if room.id < rooms|length %}
        <a href="{% url 'book:room' room.id|add:'1' %}">
            <button class="btn btn-warning">Another Room</button>
        </a>
    {% else %}
        <a href="{% url 'book:room' 1 %}">
            <button class="btn btn-warning">Another Room</button>
        </a>
    {% endif %}

    <br/>
    <p class="text-danger lead">{{ message }}</p>
{% endblock %}

BookConferenceHallApp/templates/Book/search.html
{% extends "Book/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
<br/>
<h2>Halls available in the period: {{ date }} meeting the requirements:</h2>
<br/>
<table class="table table-bordered table-striped">
    <thead class="lead">
        <tr>
            <th>Conference Hall:</th>
            <th>Capacity:</th>
            <th>Projector:</th>
        </tr>
    </thead>
    <tbody>
    {% for result in results %}
        <tr>
            <td><a href="{% url 'book:Hall' result.id %}">{{ result.name }}</a></td>
            <td>{{ result.capacity }}</td>
            <td>
                {% if result.projector == True %}
                Yes
                {% else %}
                No
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<br/>
<p class="text-danger">*Clicking on the name of the Hall will take you to the booking page</p>


{% endblock %}